# src/rl_fzerox/core/training/runs/baseline_materializer/materialize.py
from __future__ import annotations

import json
import os
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Protocol

from rl_fzerox.core.config.schema import (
    CurriculumConfig,
    CurriculumStageConfig,
    TrackSamplingConfig,
    TrainAppConfig,
)
from rl_fzerox.core.config.vehicle_catalog import vehicle_by_id
from rl_fzerox.core.training.runs.baseline_race_start import RaceStartVariant
from rl_fzerox.core.training.runs.paths import RunPaths
from rl_fzerox.core.training.runs.track_baselines import (
    single_active_track_entry,
    track_config_from_sampling_entry,
)

from .cache import (
    atomic_write_json,
    cache_metadata,
    cache_payload,
    cache_write_lock,
    run_state_path,
    sha256_bytes,
    sha256_json,
)
from .models import BaselineArtifact, BaselineMaterializerContext, BaselineRequest
from .requests import can_generate_track_config, request_from_track_config, request_from_track_entry
from .settings import BASELINE_MATERIALIZER_SETTINGS

_RaceStartMaterializer = Callable[..., None]


class _StateSavingEmulator(Protocol):
    def save_state(self, path: Path) -> None: ...

    def close(self) -> None: ...


def materialize_run_baselines_impl(
    config: TrainAppConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path | None,
    emulator_type: Callable[..., _StateSavingEmulator],
    race_start_materializer: _RaceStartMaterializer,
) -> TrainAppConfig:
    resolved_cache_root = (
        (cache_root or BASELINE_MATERIALIZER_SETTINGS.cache_root).expanduser().resolve()
    )
    context = BaselineMaterializerContext(
        core_path=config.emulator.core_path,
        rom_path=config.emulator.rom_path,
        renderer=config.emulator.renderer,
        race_intro_target_timer=config.env.race_intro_target_timer,
    )
    track_config = config.track
    emulator_baseline_path = config.emulator.baseline_state_path
    emulator_baseline_artifact: BaselineArtifact | None = None
    if not config.env.track_sampling.enabled and can_generate_track_config(track_config):
        emulator_baseline_artifact = materialize_baseline_impl(
            request_from_track_config(
                track_config,
                camera_setting=config.env.camera_setting,
                fallback_label="track",
            ),
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
            emulator_type=emulator_type,
            race_start_materializer=race_start_materializer,
        )
        emulator_baseline_path = emulator_baseline_artifact.state_path
        track_config = track_config.model_copy(
            update={"baseline_state_path": emulator_baseline_artifact.state_path}
        )
    elif track_config.baseline_state_path is not None:
        emulator_baseline_artifact = materialize_baseline_impl(
            request_from_track_config(
                track_config,
                camera_setting=config.env.camera_setting,
                fallback_label="track",
            ),
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
            emulator_type=emulator_type,
            race_start_materializer=race_start_materializer,
        )
        emulator_baseline_path = emulator_baseline_artifact.state_path
    if emulator_baseline_path is not None and emulator_baseline_artifact is None:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {emulator_baseline_path}"
        )

    track_sampling_config = _materialize_track_sampling(
        config.env.track_sampling,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        emulator_type=emulator_type,
        race_start_materializer=race_start_materializer,
    )
    single_track_entry = single_active_track_entry(track_sampling_config)
    if single_track_entry is not None:
        track_config = track_config_from_sampling_entry(
            single_track_entry,
            fallback=track_config,
        )

    env_config = config.env.model_copy(update={"track_sampling": track_sampling_config})
    curriculum_config = _materialize_curriculum(
        config.curriculum,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        emulator_type=emulator_type,
        race_start_materializer=race_start_materializer,
    )

    return config.model_copy(
        update={
            "track": track_config,
            "emulator": config.emulator.model_copy(
                update={
                    "runtime_dir": run_paths.runtime_root,
                    "baseline_state_path": emulator_baseline_path,
                }
            ),
            "env": env_config,
            "curriculum": curriculum_config,
        }
    )


def materialize_baseline_impl(
    request: BaselineRequest,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., _StateSavingEmulator],
    race_start_materializer: _RaceStartMaterializer,
) -> BaselineArtifact:
    reused_artifact = _reuse_existing_run_baseline(request, run_paths=run_paths)
    if reused_artifact is not None:
        return reused_artifact

    materializer_mode = _materializer_mode(request)
    payload = cache_payload(
        request,
        materializer_mode=materializer_mode,
        context=context,
    )
    cache_key = sha256_json(payload)
    cache_state_path = cache_root / f"{cache_key}.state"
    cache_metadata_path = cache_root / f"{cache_key}.json"
    if not cache_state_path.is_file() or not cache_metadata_path.is_file():
        with cache_write_lock(cache_state_path):
            if not cache_state_path.is_file():
                cache_root.mkdir(parents=True, exist_ok=True)
                materialized_sha256 = _generate_race_start_variant_state(
                    request,
                    cache_state_path=cache_state_path,
                    cache_root=cache_root,
                    context=context,
                    emulator_type=emulator_type,
                    race_start_materializer=race_start_materializer,
                )
            else:
                materialized_sha256 = sha256_bytes(cache_state_path.read_bytes())
            if not cache_metadata_path.is_file():
                atomic_write_json(
                    cache_metadata_path,
                    cache_metadata(
                        request,
                        cache_payload=payload,
                        cache_key=cache_key,
                        materializer_mode=materializer_mode,
                        materialized_state_sha256=materialized_sha256,
                    ),
                )

    target_state_path = run_state_path(run_paths, label=request.label, cache_key=cache_key)
    target_metadata_path = target_state_path.with_suffix(".json")
    target_state_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cache_state_path, target_state_path)
    shutil.copy2(cache_metadata_path, target_metadata_path)
    return BaselineArtifact(
        state_path=target_state_path,
        metadata_path=target_metadata_path,
        cache_key=cache_key,
    )


def _reuse_existing_run_baseline(
    request: BaselineRequest,
    *,
    run_paths: RunPaths,
) -> BaselineArtifact | None:
    if run_paths.fresh_run or request.source_state_path is None:
        return None

    source_state_path = request.source_state_path.expanduser().resolve()
    baselines_dir = run_paths.baselines_dir.expanduser().resolve()
    if not source_state_path.is_relative_to(baselines_dir):
        return None
    if not source_state_path.is_file():
        raise FileNotFoundError(
            f"In-place continuation baseline state not found: {source_state_path}"
        )

    metadata_path = source_state_path.with_suffix(".json")
    if not metadata_path.is_file():
        raise FileNotFoundError(
            "In-place continuation baseline metadata not found: "
            f"{metadata_path}"
        )

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    cache_key = metadata.get("cache_key")
    if not isinstance(cache_key, str) or not cache_key:
        raise ValueError(
            f"In-place continuation baseline metadata is missing cache_key: {metadata_path}"
        )

    return BaselineArtifact(
        state_path=source_state_path,
        metadata_path=metadata_path,
        cache_key=cache_key,
    )


def _materialize_curriculum(
    config: CurriculumConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., _StateSavingEmulator],
    race_start_materializer: _RaceStartMaterializer,
) -> CurriculumConfig:
    stages: list[CurriculumStageConfig] = []
    changed = False
    for stage in config.stages:
        if stage.track_sampling is None:
            stages.append(stage)
            continue
        changed = True
        stages.append(
            stage.model_copy(
                update={
                    "track_sampling": _materialize_track_sampling(
                        stage.track_sampling,
                        run_paths=run_paths,
                        cache_root=cache_root,
                        camera_setting=camera_setting,
                        context=context,
                        emulator_type=emulator_type,
                        race_start_materializer=race_start_materializer,
                    )
                }
            )
        )
    if not changed:
        return config
    return config.model_copy(update={"stages": tuple(stages)})


def _materialize_track_sampling(
    config: TrackSamplingConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., _StateSavingEmulator],
    race_start_materializer: _RaceStartMaterializer,
) -> TrackSamplingConfig:
    if not config.entries:
        return config
    entries = tuple(
        entry.model_copy(
            update={
                "baseline_state_path": materialize_baseline_impl(
                    request_from_track_entry(entry, camera_setting=camera_setting),
                    run_paths=run_paths,
                    cache_root=cache_root,
                    context=context,
                    emulator_type=emulator_type,
                    race_start_materializer=race_start_materializer,
                ).state_path
            }
        )
        for entry in config.entries
    )
    return config.model_copy(update={"entries": entries})


def _materializer_mode(request: BaselineRequest) -> str:
    if request.source_state_path is not None:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {request.source_state_path}"
        )
    return BASELINE_MATERIALIZER_SETTINGS.boot_menu_time_attack_mode


def _generate_race_start_variant_state(
    request: BaselineRequest,
    *,
    cache_state_path: Path,
    cache_root: Path,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., _StateSavingEmulator],
    race_start_materializer: _RaceStartMaterializer,
) -> str:
    if request.engine_setting_raw_value is None:
        raise ValueError("engine_setting_raw_value is required for race-start generation")
    if request.course_index is None:
        raise ValueError("course_index is required for race-start generation")
    if request.mode is None:
        raise ValueError("mode is required for race-start generation")
    if request.vehicle is None:
        raise ValueError("vehicle is required for race-start generation")
    vehicle = vehicle_by_id(request.vehicle)

    runtime_dir = cache_root / "runtime" / cache_state_path.stem
    runtime_dir.mkdir(parents=True, exist_ok=True)
    tmp_state_path = cache_state_path.with_name(
        f".{cache_state_path.stem}.{os.getpid()}.tmp{cache_state_path.suffix}"
    )
    emulator = emulator_type(
        core_path=context.core_path,
        rom_path=context.rom_path,
        runtime_dir=runtime_dir,
        baseline_state_path=None,
        renderer=context.renderer,
    )
    try:
        race_start_materializer(
            emulator=emulator,
            variant=RaceStartVariant(
                course_index=request.course_index,
                mode=request.mode,
                character_index=vehicle.character_index,
                machine_select_slot=vehicle.machine_select_slot,
                engine_setting_raw_value=request.engine_setting_raw_value,
                race_intro_target_timer=context.race_intro_target_timer,
            ),
        )
        emulator.save_state(tmp_state_path)
    finally:
        emulator.close()
    os.replace(tmp_state_path, cache_state_path)
    return sha256_bytes(cache_state_path.read_bytes())
