# src/rl_fzerox/core/training/runs/baseline_materializer.py
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path

from fzerox_emulator import Emulator
from rl_fzerox.core.config.paths import project_root_dir
from rl_fzerox.core.config.schema import (
    CurriculumConfig,
    CurriculumStageConfig,
    TrackConfig,
    TrackSamplingConfig,
    TrackSamplingEntryConfig,
    TrainAppConfig,
    VehicleMachineConfig,
)
from rl_fzerox.core.training.runs.baseline_race_start import (
    RaceStartVariant,
    materialize_time_attack_race_start_from_boot,
)
from rl_fzerox.core.training.runs.paths import RunPaths
from rl_fzerox.core.training.runs.track_baselines import (
    single_active_track_entry,
    track_config_from_sampling_entry,
)


@dataclass(frozen=True, slots=True)
class BaselineMaterializerSettings:
    """Stable materializer settings that affect cache identity and filenames."""

    schema_version: int = 7
    boot_menu_time_attack_mode: str = "boot_menu_time_attack"
    cache_root: Path = field(
        default_factory=lambda: project_root_dir() / "local" / "cache" / "baseline_materializer"
    )
    safe_name_pattern: re.Pattern[str] = field(
        default_factory=lambda: re.compile(r"[^a-zA-Z0-9_.-]+")
    )


BASELINE_MATERIALIZER_SETTINGS = BaselineMaterializerSettings()


@dataclass(frozen=True, slots=True)
class BaselineRequest:
    """Resolved input needed to generate one run-local reset state."""

    label: str
    source_state_path: Path | None = None
    course_id: str | None = None
    course_name: str | None = None
    course_index: int | None = None
    mode: str | None = None
    vehicle: str | None = None
    vehicle_name: str | None = None
    source_vehicle: str | None = None
    engine_setting: str | None = None
    engine_setting_raw_value: int | None = None
    source_course_index: int | None = None
    source_engine_setting: str | None = None
    source_engine_setting_raw_value: int | None = None
    vehicle_machine: dict[str, object] | None = None
    camera_setting: str | None = None


@dataclass(frozen=True, slots=True)
class BaselineArtifact:
    """Run-local materialized baseline artifact and metadata paths."""

    state_path: Path
    metadata_path: Path
    cache_key: str


@dataclass(frozen=True, slots=True)
class BaselineMaterializerContext:
    """Runtime dependencies needed when a materialized state must be generated."""

    core_path: Path
    rom_path: Path
    renderer: str
    race_intro_target_timer: int | None


def materialize_run_baselines(
    config: TrainAppConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path | None = None,
) -> TrainAppConfig:
    """Generate run-local baseline state artifacts for the current run."""

    resolved_cache_root = (
        (cache_root or BASELINE_MATERIALIZER_SETTINGS.cache_root).expanduser().resolve()
    )
    context = BaselineMaterializerContext(
        core_path=config.emulator.core_path,
        rom_path=config.emulator.rom_path,
        renderer=config.emulator.renderer,
        race_intro_target_timer=config.env.race_intro_target_timer,
    )
    track_config = config.track
    emulator_baseline_path = config.emulator.baseline_state_path
    generated_emulator_baseline = False
    if not config.env.track_sampling.enabled and _can_generate_track_config(track_config):
        artifact = materialize_baseline(
            _request_from_track_config(
                track_config,
                camera_setting=config.env.camera_setting,
                fallback_label="track",
            ),
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
        )
        emulator_baseline_path = artifact.state_path
        generated_emulator_baseline = True
        track_config = track_config.model_copy(update={"baseline_state_path": artifact.state_path})
    elif track_config.baseline_state_path is not None:
        materialize_baseline(
            _request_from_track_config(
                track_config,
                camera_setting=config.env.camera_setting,
                fallback_label="track",
            ),
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
        )
    if emulator_baseline_path is not None and not generated_emulator_baseline:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {emulator_baseline_path}"
        )

    track_sampling_config = _materialize_track_sampling(
        config.env.track_sampling,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
    )
    single_track_entry = single_active_track_entry(track_sampling_config)
    if single_track_entry is not None:
        track_config = track_config_from_sampling_entry(
            single_track_entry,
            fallback=track_config,
        )

    env_config = config.env.model_copy(update={"track_sampling": track_sampling_config})
    curriculum_config = _materialize_curriculum(
        config.curriculum,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
    )

    return config.model_copy(
        update={
            "track": track_config,
            "emulator": config.emulator.model_copy(
                update={
                    "runtime_dir": run_paths.runtime_root,
                    "baseline_state_path": emulator_baseline_path,
                }
            ),
            "env": env_config,
            "curriculum": curriculum_config,
        }
    )


def materialize_baseline(
    request: BaselineRequest,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    context: BaselineMaterializerContext,
) -> BaselineArtifact:
    """Ensure one generated baseline exists in cache and copy it into the run."""

    materializer_mode = _materializer_mode(request)
    cache_payload = _cache_payload(
        request,
        materializer_mode=materializer_mode,
        context=context,
    )
    cache_key = _sha256_json(cache_payload)
    cache_state_path = cache_root / f"{cache_key}.state"
    cache_metadata_path = cache_root / f"{cache_key}.json"
    if not cache_state_path.is_file():
        cache_root.mkdir(parents=True, exist_ok=True)
        materialized_sha256 = _generate_race_start_variant_state(
            request,
            cache_state_path=cache_state_path,
            cache_root=cache_root,
            context=context,
        )
        _atomic_write_json(
            cache_metadata_path,
            _cache_metadata(
                request,
                cache_payload=cache_payload,
                cache_key=cache_key,
                materializer_mode=materializer_mode,
                materialized_state_sha256=materialized_sha256,
            ),
        )
    elif not cache_metadata_path.is_file():
        cache_root.mkdir(parents=True, exist_ok=True)
        _atomic_write_json(
            cache_metadata_path,
            _cache_metadata(
                request,
                cache_payload=cache_payload,
                cache_key=cache_key,
                materializer_mode=materializer_mode,
                materialized_state_sha256=_sha256_bytes(cache_state_path.read_bytes()),
            ),
        )

    run_state_path = _run_state_path(run_paths, label=request.label, cache_key=cache_key)
    run_metadata_path = run_state_path.with_suffix(".json")
    run_state_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cache_state_path, run_state_path)
    shutil.copy2(cache_metadata_path, run_metadata_path)
    return BaselineArtifact(
        state_path=run_state_path,
        metadata_path=run_metadata_path,
        cache_key=cache_key,
    )


def _materialize_curriculum(
    config: CurriculumConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
) -> CurriculumConfig:
    stages: list[CurriculumStageConfig] = []
    changed = False
    for stage in config.stages:
        if stage.track_sampling is None:
            stages.append(stage)
            continue
        changed = True
        stages.append(
            stage.model_copy(
                update={
                    "track_sampling": _materialize_track_sampling(
                        stage.track_sampling,
                        run_paths=run_paths,
                        cache_root=cache_root,
                        camera_setting=camera_setting,
                        context=context,
                    )
                }
            )
        )
    if not changed:
        return config
    return config.model_copy(update={"stages": tuple(stages)})


def _materialize_track_sampling(
    config: TrackSamplingConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
) -> TrackSamplingConfig:
    if not config.entries:
        return config
    entries = tuple(
        entry.model_copy(
            update={
                "baseline_state_path": materialize_baseline(
                    _request_from_track_entry(entry, camera_setting=camera_setting),
                    run_paths=run_paths,
                    cache_root=cache_root,
                    context=context,
                ).state_path
            }
        )
        for entry in config.entries
    )
    return config.model_copy(update={"entries": entries})


def _request_from_track_config(
    track: TrackConfig,
    *,
    camera_setting: str | None,
    fallback_label: str,
) -> BaselineRequest:
    return BaselineRequest(
        label=track.id or track.course_id or fallback_label,
        source_state_path=track.baseline_state_path,
        course_id=track.course_id or track.id,
        course_name=track.course_name or track.display_name,
        course_index=track.course_index,
        mode=track.mode,
        vehicle=track.vehicle,
        vehicle_name=track.vehicle_name,
        source_vehicle=track.source_vehicle,
        engine_setting=track.engine_setting,
        engine_setting_raw_value=track.engine_setting_raw_value,
        source_course_index=track.source_course_index,
        source_engine_setting=track.source_engine_setting,
        source_engine_setting_raw_value=track.source_engine_setting_raw_value,
        vehicle_machine=_vehicle_machine_data(track.vehicle_machine),
        camera_setting=camera_setting,
    )


def _can_generate_track_config(track: TrackConfig) -> bool:
    return (
        track.course_index is not None
        and track.mode is not None
        and track.vehicle is not None
        and track.engine_setting_raw_value is not None
        and track.vehicle_machine is not None
    )


def _request_from_track_entry(
    entry: TrackSamplingEntryConfig,
    *,
    camera_setting: str | None,
) -> BaselineRequest:
    return BaselineRequest(
        label=entry.id,
        source_state_path=entry.baseline_state_path,
        course_id=entry.course_id,
        course_name=entry.course_name or entry.display_name,
        course_index=entry.course_index,
        mode=entry.mode,
        vehicle=entry.vehicle,
        vehicle_name=entry.vehicle_name,
        source_vehicle=entry.source_vehicle,
        engine_setting=entry.engine_setting,
        engine_setting_raw_value=entry.engine_setting_raw_value,
        source_course_index=entry.source_course_index,
        source_engine_setting=entry.source_engine_setting,
        source_engine_setting_raw_value=entry.source_engine_setting_raw_value,
        vehicle_machine=_vehicle_machine_data(entry.vehicle_machine),
        camera_setting=camera_setting,
    )


def _materializer_mode(request: BaselineRequest) -> str:
    if request.source_state_path is not None:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {request.source_state_path}"
        )
    return BASELINE_MATERIALIZER_SETTINGS.boot_menu_time_attack_mode


def _generate_race_start_variant_state(
    request: BaselineRequest,
    *,
    cache_state_path: Path,
    cache_root: Path,
    context: BaselineMaterializerContext,
) -> str:
    if request.engine_setting_raw_value is None:
        raise ValueError("engine_setting_raw_value is required for race-start generation")
    if request.course_index is None:
        raise ValueError("course_index is required for race-start generation")
    if request.mode is None:
        raise ValueError("mode is required for race-start generation")
    if request.vehicle_machine is None:
        raise ValueError("vehicle_machine is required for race-start generation")

    runtime_dir = cache_root / "runtime" / cache_state_path.stem
    runtime_dir.mkdir(parents=True, exist_ok=True)
    tmp_state_path = cache_state_path.with_name(
        f".{cache_state_path.stem}.tmp{cache_state_path.suffix}"
    )
    emulator = Emulator(
        core_path=context.core_path,
        rom_path=context.rom_path,
        runtime_dir=runtime_dir,
        baseline_state_path=None,
        renderer=context.renderer,
    )
    try:
        materialize_time_attack_race_start_from_boot(
            emulator=emulator,
            variant=RaceStartVariant(
                course_index=request.course_index,
                mode=request.mode,
                character_index=_required_int(request.vehicle_machine, "character_index"),
                machine_select_slot=_optional_int(
                    request.vehicle_machine,
                    "machine_select_slot",
                ),
                engine_setting_raw_value=request.engine_setting_raw_value,
                race_intro_target_timer=context.race_intro_target_timer,
            ),
        )
        emulator.save_state(tmp_state_path)
    finally:
        emulator.close()
    os.replace(tmp_state_path, cache_state_path)
    return _sha256_bytes(cache_state_path.read_bytes())


def _vehicle_machine_data(machine: VehicleMachineConfig | None) -> dict[str, object] | None:
    if machine is None:
        return None
    return machine.model_dump(mode="json")


def _required_int(data: dict[str, object], key: str) -> int:
    value = data.get(key)
    if isinstance(value, bool) or not isinstance(value, int | float | str):
        raise ValueError(f"vehicle_machine.{key} must be numeric")
    return int(value)


def _optional_int(data: dict[str, object], key: str) -> int | None:
    value = data.get(key)
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int | float | str):
        raise ValueError(f"vehicle_machine.{key} must be numeric when set")
    return int(value)


def _cache_payload(
    request: BaselineRequest,
    *,
    materializer_mode: str,
    context: BaselineMaterializerContext,
) -> dict[str, object]:
    return {
        "schema_version": BASELINE_MATERIALIZER_SETTINGS.schema_version,
        "materializer_mode": materializer_mode,
        "target": _target_variant_cache_data(request, context=context),
    }


def _target_variant_cache_data(
    request: BaselineRequest,
    *,
    context: BaselineMaterializerContext,
) -> dict[str, object]:
    return {
        "camera_setting": request.camera_setting,
        "course_id": request.course_id,
        "course_index": request.course_index,
        "engine_setting": request.engine_setting,
        "engine_setting_raw_value": request.engine_setting_raw_value,
        "mode": request.mode,
        "race_intro_target_timer": context.race_intro_target_timer,
        "renderer": context.renderer,
        "vehicle": request.vehicle,
        "vehicle_machine": request.vehicle_machine,
    }


def _cache_metadata(
    request: BaselineRequest,
    *,
    cache_payload: dict[str, object],
    cache_key: str,
    materializer_mode: str,
    materialized_state_sha256: str,
) -> dict[str, object]:
    return {
        **cache_payload,
        "cache_key": cache_key,
        "materializer_mode": materializer_mode,
        "materialized_state_sha256": materialized_state_sha256,
        "request": _request_metadata(request),
    }


def _request_metadata(request: BaselineRequest) -> dict[str, object]:
    request_data = asdict(request)
    if request.source_state_path is not None:
        request_data["source_state_path"] = str(request.source_state_path)
    return request_data


def _run_state_path(run_paths: RunPaths, *, label: str, cache_key: str) -> Path:
    safe_label = _safe_filename(label or "baseline")
    return run_paths.baselines_dir / f"{safe_label}__{cache_key[:12]}.state"


def _safe_filename(value: str) -> str:
    stripped = BASELINE_MATERIALIZER_SETTINGS.safe_name_pattern.sub("_", value).strip("._")
    return stripped or "baseline"


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_json(data: dict[str, object]) -> str:
    encoded = json.dumps(data, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256_bytes(encoded)


def _atomic_write_json(target_path: Path, data: dict[str, object]) -> None:
    tmp_path = target_path.with_name(f".{target_path.stem}.tmp{target_path.suffix}")
    tmp_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp_path, target_path)
