# src/fzerox_emulator/_native.pyi
"""Typing surface for the compiled `fzerox_emulator._native` PyO3 extension."""

from typing import Literal

import numpy as np
import numpy.typing as npt

from fzerox_emulator.boundary import (
    FrameObservationOptionsDict,
    FZeroXTelemetryDict,
    ObservationSpecDict,
    PlayerTelemetryDict,
    RaceStartRequestDict,
    RepeatMultiObservationStepRequestDict,
    RepeatObservationStepRequestDict,
    StepStatusDict,
    StepSummaryDict,
    VehicleSetupInfoDict,
)

class PlayerTelemetry:
    def __init__(self, data: PlayerTelemetryDict) -> None: ...
    @property
    def state_flags(self) -> int: ...
    @property
    def state_labels(self) -> tuple[str, ...]: ...
    @property
    def speed_kph(self) -> float: ...
    @property
    def energy(self) -> float: ...
    @property
    def max_energy(self) -> float: ...
    @property
    def ko_star_count(self) -> int: ...
    @property
    def boost_timer(self) -> int: ...
    @property
    def recoil_tilt_magnitude(self) -> float: ...
    @property
    def damage_rumble_counter(self) -> int: ...
    @property
    def reverse_timer(self) -> int: ...
    @property
    def race_distance(self) -> float: ...
    @property
    def lap_distance(self) -> float: ...
    @property
    def race_time_ms(self) -> int: ...
    @property
    def lap(self) -> int: ...
    @property
    def laps_completed(self) -> int: ...
    @property
    def position(self) -> int: ...
    @property
    def segment_index(self) -> int | None: ...
    @property
    def segment_t(self) -> float: ...
    @property
    def segment_length_proportion(self) -> float: ...
    @property
    def world_pos_x(self) -> float: ...
    @property
    def world_pos_y(self) -> float: ...
    @property
    def world_pos_z(self) -> float: ...
    @property
    def segment_center_x(self) -> float: ...
    @property
    def segment_center_y(self) -> float: ...
    @property
    def segment_center_z(self) -> float: ...
    @property
    def local_lateral_velocity(self) -> float: ...
    @property
    def signed_lateral_offset(self) -> float: ...
    @property
    def lateral_distance(self) -> float: ...
    @property
    def lateral_displacement_magnitude(self) -> float: ...
    @property
    def current_radius_left(self) -> float: ...
    @property
    def current_radius_right(self) -> float: ...
    @property
    def height_above_ground(self) -> float: ...
    @property
    def future_local_nearest_segment_index(self) -> int | None: ...
    @property
    def future_local_nearest_segment_distance(self) -> float: ...
    @property
    def velocity_magnitude(self) -> float: ...
    @property
    def acceleration_magnitude(self) -> float: ...
    @property
    def acceleration_force(self) -> float: ...
    @property
    def drift_attack_force(self) -> float: ...
    @property
    def collision_mass(self) -> float: ...
    @property
    def machine_character_index(self) -> int: ...
    @property
    def machine_body_stat(self) -> int: ...
    @property
    def machine_boost_stat(self) -> int: ...
    @property
    def machine_grip_stat(self) -> int: ...
    @property
    def machine_weight(self) -> int: ...
    @property
    def engine_setting(self) -> float: ...
    @property
    def collision_recoil(self) -> bool: ...
    @property
    def spinning_out(self) -> bool: ...
    @property
    def retired(self) -> bool: ...
    @property
    def falling_off_track(self) -> bool: ...
    @property
    def can_boost(self) -> bool: ...
    @property
    def cpu_controlled(self) -> bool: ...
    @property
    def dash_pad_boost(self) -> bool: ...
    @property
    def finished(self) -> bool: ...
    @property
    def airborne(self) -> bool: ...
    @property
    def crashed(self) -> bool: ...
    @property
    def active(self) -> bool: ...
    @property
    def course_effect_raw(self) -> int: ...
    @property
    def course_effect_name(self) -> str: ...
    @property
    def on_energy_refill(self) -> bool: ...
    @property
    def terminal_reason(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

class FZeroXTelemetry:
    def __init__(self, data: FZeroXTelemetryDict) -> None: ...
    @property
    def total_lap_count(self) -> int: ...
    @property
    def difficulty_raw(self) -> int: ...
    @property
    def difficulty_name(self) -> str: ...
    @property
    def camera_setting_raw(self) -> int: ...
    @property
    def camera_setting_name(self) -> str: ...
    @property
    def race_intro_timer(self) -> int: ...
    @property
    def game_mode_raw(self) -> int: ...
    @property
    def game_mode_name(self) -> str: ...
    @property
    def menu_selected_mode_raw(self) -> int: ...
    @property
    def menu_difficulty_state_raw(self) -> int: ...
    @property
    def menu_difficulty_cursor_raw(self) -> int: ...
    @property
    def menu_transition_state_raw(self) -> int: ...
    @property
    def menu_current_ghost_type_raw(self) -> int: ...
    @property
    def queued_game_mode_raw(self) -> int: ...
    @property
    def in_race_mode(self) -> bool: ...
    @property
    def total_racers(self) -> int: ...
    @property
    def gp_final_rank(self) -> int: ...
    @property
    def course_index(self) -> int: ...
    @property
    def course_segment_count(self) -> int: ...
    @property
    def course_length(self) -> float: ...
    @property
    def player(self) -> PlayerTelemetry: ...
    def to_dict(self) -> dict[str, object]: ...

class StepSummary:
    def __init__(self, data: StepSummaryDict) -> None: ...
    @property
    def frames_run(self) -> int: ...
    @property
    def max_race_distance(self) -> float: ...
    @property
    def max_race_distance_speed_kph(self) -> float: ...
    @property
    def reverse_active_frames(self) -> int: ...
    @property
    def collision_recoil_active_frames(self) -> int: ...
    @property
    def low_speed_frames(self) -> int: ...
    @property
    def energy_loss_total(self) -> float: ...
    @property
    def energy_gain_total(self) -> float: ...
    @property
    def damage_taken_frames(self) -> int: ...
    @property
    def impact_frames(self) -> int: ...
    @property
    def airborne_frames(self) -> int: ...
    @property
    def outside_track_min_height_above_ground(self) -> float | None: ...
    @property
    def spin_macro_started(self) -> bool: ...
    @property
    def spin_macro_active_frames(self) -> int: ...
    @property
    def lean_macro_owned_frames(self) -> int: ...
    @property
    def consecutive_low_speed_frames(self) -> int: ...
    @property
    def entered_state_flags(self) -> int: ...
    @property
    def entered_course_effects(self) -> int: ...
    @property
    def entered_state_labels(self) -> tuple[str, ...]: ...
    @property
    def entered_spinning_out(self) -> bool: ...
    @property
    def entered_falling_off_track(self) -> bool: ...
    @property
    def entered_crashed(self) -> bool: ...
    @property
    def entered_retired(self) -> bool: ...
    @property
    def entered_finished(self) -> bool: ...
    @property
    def entered_dash_pad_boost(self) -> bool: ...
    @property
    def entered_dash_surface(self) -> bool: ...
    @property
    def final_frame_index(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

class StepStatus:
    def __init__(self, data: StepStatusDict) -> None: ...
    @property
    def step_count(self) -> int: ...
    @property
    def stalled_steps(self) -> int: ...
    @property
    def reverse_timer(self) -> int: ...
    @property
    def progress_frontier_stalled_frames(self) -> int: ...
    @property
    def terminated(self) -> bool: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def termination_reason(self) -> str | None: ...
    @property
    def truncation_reason(self) -> str | None: ...
    @property
    def spin_macro_active(self) -> bool: ...
    @property
    def spin_macro_frames_remaining(self) -> int: ...
    @property
    def spin_macro_cooldown_frames(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

class Emulator:
    def __init__(
        self,
        core_path: str,
        rom_path: str,
        runtime_dir: str | None = None,
        baseline_state_path: str | None = None,
        renderer: str = "angrylion",
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def native_fps(self) -> float: ...
    @property
    def native_sample_rate(self) -> float: ...
    @property
    def display_aspect_ratio(self) -> float: ...
    @property
    def frame_shape(self) -> tuple[int, int, int]: ...
    @property
    def frame_index(self) -> int: ...
    @property
    def system_ram_size(self) -> int: ...
    @property
    def baseline_kind(self) -> str: ...
    def reset(self) -> None: ...
    def step_frames(self, count: int = 1, capture_video: bool = True) -> None: ...
    def step_frames_with_audio(
        self,
        count: int = 1,
        capture_video: bool = True,
    ) -> npt.NDArray[np.int16]: ...
    def step_repeat_raw(
        self,
        request: RepeatObservationStepRequestDict,
    ) -> tuple[npt.NDArray[np.uint8], StepSummary, StepStatus, FZeroXTelemetry]: ...
    def step_repeat_multi_observation_raw(
        self,
        request: RepeatMultiObservationStepRequestDict,
    ) -> tuple[list[npt.NDArray[np.uint8]], StepSummary, StepStatus, FZeroXTelemetry]: ...
    def step_repeat_watch_raw(
        self,
        request: RepeatObservationStepRequestDict,
    ) -> tuple[
        npt.NDArray[np.uint8],
        npt.NDArray[np.uint8],
        npt.NDArray[np.uint16],
        npt.NDArray[np.int16],
        npt.NDArray[np.uint32],
        StepSummary,
        StepStatus,
        FZeroXTelemetry,
    ]: ...
    def set_controller_state(
        self,
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> None: ...
    def save_state(self, path: str) -> None: ...
    def load_baseline(self, path: str) -> None: ...
    def load_baseline_bytes(self, state: bytes) -> None: ...
    def capture_current_as_baseline(self, path: str | None = None) -> None: ...
    def frame_rgb(self) -> npt.NDArray[np.uint8]: ...
    def observation_spec(
        self,
        preset: str,
        *,
        height: int | None = None,
        width: int | None = None,
    ) -> ObservationSpecDict: ...
    def frame_observation(
        self,
        preset: str,
        frame_stack: int,
        options: FrameObservationOptionsDict | None = None,
    ) -> npt.NDArray[np.uint8]: ...
    def frame_display(
        self,
        preset: str,
        *,
        height: int | None = None,
        width: int | None = None,
    ) -> npt.NDArray[np.uint8]: ...
    def telemetry(self) -> FZeroXTelemetry | None: ...
    def patch_race_start_setup(self, request: RaceStartRequestDict) -> None: ...
    def patch_machine_settings(self, request: RaceStartRequestDict) -> None: ...
    def patch_engine_settings(self, mode: str, engine_setting_raw_value: int) -> None: ...
    def force_race_reinit(self, mode: str) -> None: ...
    def validate_race_start_setup(self, request: RaceStartRequestDict) -> None: ...
    def patch_time_attack_menu_mode(self) -> None: ...
    def vehicle_setup_info(self) -> VehicleSetupInfoDict: ...
    def read_system_ram(self, offset: int, length: int) -> bytes: ...
    def write_system_ram(self, offset: int, data: bytes) -> None: ...
    def save_ram_size(self) -> int: ...
    def read_save_ram(self) -> bytes: ...
    def write_save_ram(self, data: bytes) -> None: ...
    def game_rng_state(self) -> tuple[int, int, int, int]: ...
    def randomize_game_rng(self, seed: int) -> tuple[int, int, int, int]: ...
    def close(self) -> None: ...

class CoreInfo:
    api_version: int
    library_name: str
    library_version: str
    valid_extensions: list[str]
    requires_full_path: bool
    blocks_extract: bool

# Load a libretro core and read metadata without booting content or reading RAM.
def probe_core(core_path: str) -> CoreInfo: ...
def encode_state_flags(labels: list[str] | tuple[str, ...]) -> int: ...
def fzerox_menu_button_mask(button: str) -> int: ...
def joypad_mask(*buttons: int) -> int: ...
def display_size(width: int, height: int, aspect_ratio: float) -> tuple[int, int]: ...
def stacked_observation_channels(
    single_frame_channels: int,
    frame_stack: int,
    stack_mode: Literal["rgb", "gray", "luma_chroma"] = "rgb",
    minimap_layer: bool = False,
) -> int: ...
