# src/fzerox_emulator/_native.pyi
from typing import Any, TypedDict

class ObservationSpecDict(TypedDict):
    preset: str
    width: int
    height: int
    channels: int
    display_width: int
    display_height: int

class PlayerTelemetry:
    def __init__(
        self,
        state_flags: int,
        speed_kph: float,
        energy: float,
        max_energy: float,
        boost_timer: int,
        race_distance: float,
        lap_distance: float,
        race_time_ms: int,
        lap: int,
        laps_completed: int,
        position: int,
    ) -> None: ...
    @property
    def state_flags(self) -> int: ...
    @property
    def state_labels(self) -> tuple[str, ...]: ...
    @property
    def speed_kph(self) -> float: ...
    @property
    def energy(self) -> float: ...
    @property
    def max_energy(self) -> float: ...
    @property
    def boost_timer(self) -> int: ...
    @property
    def race_distance(self) -> float: ...
    @property
    def lap_distance(self) -> float: ...
    @property
    def race_time_ms(self) -> int: ...
    @property
    def lap(self) -> int: ...
    @property
    def laps_completed(self) -> int: ...
    @property
    def position(self) -> int: ...
    @property
    def collision_recoil(self) -> bool: ...
    @property
    def spinning_out(self) -> bool: ...
    @property
    def retired(self) -> bool: ...
    @property
    def falling_off_track(self) -> bool: ...
    @property
    def can_boost(self) -> bool: ...
    @property
    def cpu_controlled(self) -> bool: ...
    @property
    def dash_pad_boost(self) -> bool: ...
    @property
    def finished(self) -> bool: ...
    @property
    def airborne(self) -> bool: ...
    @property
    def crashed(self) -> bool: ...
    @property
    def active(self) -> bool: ...
    @property
    def terminal_reason(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...


class FZeroXTelemetry:
    def __init__(
        self,
        game_mode_raw: int,
        game_mode_name: str,
        in_race_mode: bool,
        course_index: int,
        player: PlayerTelemetry,
    ) -> None: ...
    @property
    def game_mode_raw(self) -> int: ...
    @property
    def game_mode_name(self) -> str: ...
    @property
    def in_race_mode(self) -> bool: ...
    @property
    def course_index(self) -> int: ...
    @property
    def player(self) -> PlayerTelemetry: ...
    def to_dict(self) -> dict[str, object]: ...


class StepSummary:
    def __init__(
        self,
        frames_run: int,
        max_race_distance: float,
        reverse_progress_total: float = 0.0,
        consecutive_reverse_frames: int = 0,
        energy_loss_total: float = 0.0,
        consecutive_low_speed_frames: int = 0,
        entered_state_flags: int = 0,
        final_frame_index: int = 0,
    ) -> None: ...
    @property
    def frames_run(self) -> int: ...
    @property
    def max_race_distance(self) -> float: ...
    @property
    def reverse_progress_total(self) -> float: ...
    @property
    def consecutive_reverse_frames(self) -> int: ...
    @property
    def energy_loss_total(self) -> float: ...
    @property
    def consecutive_low_speed_frames(self) -> int: ...
    @property
    def entered_state_flags(self) -> int: ...
    @property
    def entered_state_labels(self) -> tuple[str, ...]: ...
    @property
    def entered_collision_recoil(self) -> bool: ...
    @property
    def entered_spinning_out(self) -> bool: ...
    @property
    def entered_falling_off_track(self) -> bool: ...
    @property
    def entered_crashed(self) -> bool: ...
    @property
    def entered_retired(self) -> bool: ...
    @property
    def entered_finished(self) -> bool: ...
    @property
    def entered_dash_pad_boost(self) -> bool: ...
    @property
    def final_frame_index(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...


class Emulator:
    def __init__(
        self,
        core_path: str,
        rom_path: str,
        runtime_dir: str | None = None,
        baseline_state_path: str | None = None,
        renderer: str = "angrylion",
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def native_fps(self) -> float: ...
    @property
    def display_aspect_ratio(self) -> float: ...
    @property
    def frame_shape(self) -> tuple[int, int, int]: ...
    @property
    def frame_index(self) -> int: ...
    @property
    def system_ram_size(self) -> int: ...
    @property
    def baseline_kind(self) -> str: ...
    def reset(self) -> None: ...
    def step_frames(self, count: int = 1, capture_video: bool = True) -> None: ...
    def step_repeat_raw(
        self,
        action_repeat: int,
        preset: str,
        frame_stack: int,
        stuck_min_speed_kph: float,
        reverse_progress_epsilon: float,
        energy_loss_epsilon: float,
        wrong_way_progress_epsilon: float,
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> tuple[Any, StepSummary, FZeroXTelemetry]: ...
    def set_controller_state(
        self,
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> None: ...
    def save_state(self, path: str) -> None: ...
    def capture_current_as_baseline(self, path: str | None = None) -> None: ...
    def frame_rgb(self) -> bytes: ...
    def observation_spec(self, preset: str) -> ObservationSpecDict: ...
    def frame_observation(self, preset: str, frame_stack: int) -> Any: ...
    def frame_display(self, preset: str) -> Any: ...
    def telemetry(self) -> FZeroXTelemetry | None: ...
    def read_system_ram(self, offset: int, length: int) -> bytes: ...
    def close(self) -> None: ...

class CoreInfo:
    api_version: int
    library_name: str
    library_version: str
    valid_extensions: list[str]
    requires_full_path: bool
    blocks_extract: bool

def probe_core(core_path: str) -> CoreInfo: ...
def encode_state_flags(labels: list[str] | tuple[str, ...]) -> int: ...
def joypad_mask(*buttons: int) -> int: ...

JOYPAD_B: int
JOYPAD_Y: int
JOYPAD_SELECT: int
JOYPAD_START: int
JOYPAD_UP: int
JOYPAD_DOWN: int
JOYPAD_LEFT: int
JOYPAD_RIGHT: int
JOYPAD_A: int
JOYPAD_X: int
JOYPAD_L: int
JOYPAD_R: int
JOYPAD_L2: int
JOYPAD_R2: int
JOYPAD_L3: int
JOYPAD_R3: int
