# src/fzerox_emulator/_native.pyi
from typing import Literal, TypedDict

import numpy as np
import numpy.typing as npt

class ObservationSpecDict(TypedDict):
    preset: str
    width: int
    height: int
    channels: int
    display_width: int
    display_height: int

class PlayerTelemetry:
    def __init__(
        self,
        state_flags: int,
        speed_kph: float,
        energy: float,
        max_energy: float,
        boost_timer: int,
        recoil_tilt_magnitude: float,
        reverse_timer: int,
        race_distance: float,
        lap_distance: float,
        race_time_ms: int,
        lap: int,
        laps_completed: int,
        position: int,
        damage_rumble_counter: int = 0,
        segment_index: int | None = None,
        segment_t: float = 0.0,
        segment_length_proportion: float = 0.0,
        local_lateral_velocity: float = 0.0,
        signed_lateral_offset: float = 0.0,
        lateral_distance: float = 0.0,
        lateral_displacement_magnitude: float = 0.0,
        current_radius_left: float = 0.0,
        current_radius_right: float = 0.0,
        height_above_ground: float = 0.0,
        velocity_magnitude: float = 0.0,
        acceleration_magnitude: float = 0.0,
        acceleration_force: float = 0.0,
        drift_attack_force: float = 0.0,
        collision_mass: float = 0.0,
    ) -> None: ...
    @property
    def state_flags(self) -> int: ...
    @property
    def state_labels(self) -> tuple[str, ...]: ...
    @property
    def speed_kph(self) -> float: ...
    @property
    def energy(self) -> float: ...
    @property
    def max_energy(self) -> float: ...
    @property
    def boost_timer(self) -> int: ...
    @property
    def recoil_tilt_magnitude(self) -> float: ...
    @property
    def damage_rumble_counter(self) -> int: ...
    @property
    def reverse_timer(self) -> int: ...
    @property
    def race_distance(self) -> float: ...
    @property
    def lap_distance(self) -> float: ...
    @property
    def race_time_ms(self) -> int: ...
    @property
    def lap(self) -> int: ...
    @property
    def laps_completed(self) -> int: ...
    @property
    def position(self) -> int: ...
    @property
    def segment_index(self) -> int | None: ...
    @property
    def segment_t(self) -> float: ...
    @property
    def segment_length_proportion(self) -> float: ...
    @property
    def local_lateral_velocity(self) -> float: ...
    @property
    def signed_lateral_offset(self) -> float: ...
    @property
    def lateral_distance(self) -> float: ...
    @property
    def lateral_displacement_magnitude(self) -> float: ...
    @property
    def current_radius_left(self) -> float: ...
    @property
    def current_radius_right(self) -> float: ...
    @property
    def height_above_ground(self) -> float: ...
    @property
    def velocity_magnitude(self) -> float: ...
    @property
    def acceleration_magnitude(self) -> float: ...
    @property
    def acceleration_force(self) -> float: ...
    @property
    def drift_attack_force(self) -> float: ...
    @property
    def collision_mass(self) -> float: ...
    @property
    def collision_recoil(self) -> bool: ...
    @property
    def spinning_out(self) -> bool: ...
    @property
    def retired(self) -> bool: ...
    @property
    def falling_off_track(self) -> bool: ...
    @property
    def can_boost(self) -> bool: ...
    @property
    def cpu_controlled(self) -> bool: ...
    @property
    def dash_pad_boost(self) -> bool: ...
    @property
    def finished(self) -> bool: ...
    @property
    def airborne(self) -> bool: ...
    @property
    def crashed(self) -> bool: ...
    @property
    def active(self) -> bool: ...
    @property
    def course_effect_raw(self) -> int: ...
    @property
    def course_effect_name(self) -> str: ...
    @property
    def on_energy_refill(self) -> bool: ...
    @property
    def terminal_reason(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

class FZeroXTelemetry:
    def __init__(
        self,
        total_lap_count: int,
        game_mode_raw: int,
        game_mode_name: str,
        in_race_mode: bool,
        total_racers: int,
        course_index: int,
        player: PlayerTelemetry,
        difficulty_raw: int = 0,
        difficulty_name: str | None = None,
        camera_setting_raw: int = 2,
        camera_setting_name: str | None = None,
        race_intro_timer: int = 0,
    ) -> None: ...
    @property
    def total_lap_count(self) -> int: ...
    @property
    def difficulty_raw(self) -> int: ...
    @property
    def difficulty_name(self) -> str: ...
    @property
    def camera_setting_raw(self) -> int: ...
    @property
    def camera_setting_name(self) -> str: ...
    @property
    def race_intro_timer(self) -> int: ...
    @property
    def game_mode_raw(self) -> int: ...
    @property
    def game_mode_name(self) -> str: ...
    @property
    def in_race_mode(self) -> bool: ...
    @property
    def total_racers(self) -> int: ...
    @property
    def course_index(self) -> int: ...
    @property
    def player(self) -> PlayerTelemetry: ...
    def to_dict(self) -> dict[str, object]: ...

class StepSummary:
    def __init__(
        self,
        frames_run: int,
        max_race_distance: float,
        reverse_active_frames: int = 0,
        low_speed_frames: int = 0,
        energy_loss_total: float = 0.0,
        energy_gain_total: float = 0.0,
        damage_taken_frames: int = 0,
        consecutive_low_speed_frames: int = 0,
        entered_state_flags: int = 0,
        final_frame_index: int = 0,
    ) -> None: ...
    @property
    def frames_run(self) -> int: ...
    @property
    def max_race_distance(self) -> float: ...
    @property
    def reverse_active_frames(self) -> int: ...
    @property
    def low_speed_frames(self) -> int: ...
    @property
    def energy_loss_total(self) -> float: ...
    @property
    def energy_gain_total(self) -> float: ...
    @property
    def damage_taken_frames(self) -> int: ...
    @property
    def consecutive_low_speed_frames(self) -> int: ...
    @property
    def entered_state_flags(self) -> int: ...
    @property
    def entered_state_labels(self) -> tuple[str, ...]: ...
    @property
    def entered_collision_recoil(self) -> bool: ...
    @property
    def entered_spinning_out(self) -> bool: ...
    @property
    def entered_falling_off_track(self) -> bool: ...
    @property
    def entered_crashed(self) -> bool: ...
    @property
    def entered_retired(self) -> bool: ...
    @property
    def entered_finished(self) -> bool: ...
    @property
    def entered_dash_pad_boost(self) -> bool: ...
    @property
    def final_frame_index(self) -> int: ...
    def to_dict(self) -> dict[str, object]: ...

class StepStatus:
    def __init__(
        self,
        step_count: int,
        stalled_steps: int,
        reverse_timer: int = 0,
        progress_frontier_stalled_frames: int = 0,
        termination_reason: str | None = None,
        truncation_reason: str | None = None,
    ) -> None: ...
    @property
    def step_count(self) -> int: ...
    @property
    def stalled_steps(self) -> int: ...
    @property
    def reverse_timer(self) -> int: ...
    @property
    def progress_frontier_stalled_frames(self) -> int: ...
    @property
    def terminated(self) -> bool: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def termination_reason(self) -> str | None: ...
    @property
    def truncation_reason(self) -> str | None: ...
    def to_dict(self) -> dict[str, object]: ...

class Emulator:
    def __init__(
        self,
        core_path: str,
        rom_path: str,
        runtime_dir: str | None = None,
        baseline_state_path: str | None = None,
        renderer: str = "angrylion",
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def native_fps(self) -> float: ...
    @property
    def display_aspect_ratio(self) -> float: ...
    @property
    def frame_shape(self) -> tuple[int, int, int]: ...
    @property
    def frame_index(self) -> int: ...
    @property
    def system_ram_size(self) -> int: ...
    @property
    def baseline_kind(self) -> str: ...
    def reset(self) -> None: ...
    def step_frames(self, count: int = 1, capture_video: bool = True) -> None: ...
    def step_repeat_raw(
        self,
        action_repeat: int,
        preset: str,
        frame_stack: int,
        stuck_min_speed_kph: float,
        energy_loss_epsilon: float,
        max_episode_steps: int,
        stuck_step_limit: int,
        wrong_way_timer_limit: int | None,
        progress_frontier_stall_limit_frames: int | None,
        progress_frontier_epsilon: float,
        terminate_on_energy_depleted: bool = True,
        lean_timer_assist: bool = False,
        stack_mode: Literal["rgb", "rgb_gray"] = "rgb",
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> tuple[npt.NDArray[np.uint8], StepSummary, StepStatus, FZeroXTelemetry]: ...
    def step_repeat_watch_raw(
        self,
        action_repeat: int,
        preset: str,
        frame_stack: int,
        stuck_min_speed_kph: float,
        energy_loss_epsilon: float,
        max_episode_steps: int,
        stuck_step_limit: int,
        wrong_way_timer_limit: int | None,
        progress_frontier_stall_limit_frames: int | None,
        progress_frontier_epsilon: float,
        terminate_on_energy_depleted: bool = True,
        lean_timer_assist: bool = False,
        stack_mode: Literal["rgb", "rgb_gray"] = "rgb",
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> tuple[
        npt.NDArray[np.uint8],
        list[npt.NDArray[np.uint8]],
        StepSummary,
        StepStatus,
        FZeroXTelemetry,
    ]: ...
    def set_controller_state(
        self,
        joypad_mask: int = 0,
        left_stick_x: float = 0.0,
        left_stick_y: float = 0.0,
        right_stick_x: float = 0.0,
        right_stick_y: float = 0.0,
    ) -> None: ...
    def save_state(self, path: str) -> None: ...
    def load_baseline(self, path: str) -> None: ...
    def load_baseline_bytes(self, state: bytes) -> None: ...
    def capture_current_as_baseline(self, path: str | None = None) -> None: ...
    def frame_rgb(self) -> bytes: ...
    def observation_spec(self, preset: str) -> ObservationSpecDict: ...
    def frame_observation(
        self,
        preset: str,
        frame_stack: int,
        stack_mode: Literal["rgb", "rgb_gray"] = "rgb",
    ) -> npt.NDArray[np.uint8]: ...
    def frame_display(self, preset: str) -> npt.NDArray[np.uint8]: ...
    def telemetry(self) -> FZeroXTelemetry | None: ...
    def read_system_ram(self, offset: int, length: int) -> bytes: ...
    def write_system_ram(self, offset: int, data: bytes) -> None: ...
    def game_rng_state(self) -> tuple[int, int, int, int]: ...
    def randomize_game_rng(self, seed: int) -> tuple[int, int, int, int]: ...
    def close(self) -> None: ...

class CoreInfo:
    api_version: int
    library_name: str
    library_version: str
    valid_extensions: list[str]
    requires_full_path: bool
    blocks_extract: bool

def probe_core(core_path: str) -> CoreInfo: ...
def encode_state_flags(labels: list[str] | tuple[str, ...]) -> int: ...
def joypad_mask(*buttons: int) -> int: ...

JOYPAD_B: int
JOYPAD_Y: int
JOYPAD_SELECT: int
JOYPAD_START: int
JOYPAD_UP: int
JOYPAD_DOWN: int
JOYPAD_LEFT: int
JOYPAD_RIGHT: int
JOYPAD_A: int
JOYPAD_X: int
JOYPAD_L: int
JOYPAD_R: int
JOYPAD_L2: int
JOYPAD_R2: int
JOYPAD_L3: int
JOYPAD_R3: int
