import type {
  ConfigMetadata,
  ManagedDraft,
  ManagedRunConfig,
  PolicyArchitecturePreview,
} from "@/shared/api/contract";

export const managedRunConfigFixture: ManagedRunConfig = {
  version: 1,
  seed: 123,
  preset_name: "all-cups recurrent PPO",
  train: {
    algorithm: "maskable_hybrid_recurrent_ppo",
    num_envs: 10,
    total_timesteps: 50_000_000,
    n_steps: 2048,
    n_epochs: 3,
    batch_size: 1024,
    learning_rate: 0.000085,
    gamma: 0.995,
    gae_lambda: 0.95,
    clip_range: 0.19,
    clip_range_vf: null,
    ent_coef: 0.01,
    vf_coef: 0.5,
    max_grad_norm: 0.5,
    normalize_advantage: true,
    target_kl: null,
    stats_window_size: 100,
    course_context_dropout_prob: 0,
  },
  observation: {
    preset: "crop_60x76",
    frame_stack: 2,
    stack_mode: "rgb",
    minimap_layer: false,
    resize_filter: "bilinear",
    minimap_resize_filter: "nearest",
    state_components: [
      {
        name: "vehicle_state",
        mode: "include",
        encoding: null,
        progress_source: null,
        length: null,
        controls: null,
      },
      {
        name: "machine_context",
        mode: "include",
        encoding: null,
        progress_source: null,
        length: null,
        controls: null,
      },
      {
        name: "track_position",
        mode: "include",
        encoding: null,
        progress_source: "segment_progress",
        length: null,
        controls: null,
      },
      {
        name: "surface_state",
        mode: "include",
        encoding: null,
        progress_source: null,
        length: null,
        controls: null,
      },
      {
        name: "course_context",
        mode: "include",
        encoding: "one_hot_builtin",
        progress_source: null,
        length: null,
        controls: null,
      },
      {
        name: "control_history",
        mode: "include",
        encoding: null,
        progress_source: null,
        length: 1,
        controls: ["steer", "thrust", "air_brake", "boost", "lean", "pitch"],
      },
    ],
    state_feature_modes: [
      { name: "track_position.edge_ratio", mode: "zero" },
      { name: "track_position.outside_track_bounds", mode: "zero" },
    ],
  },
  policy: {
    conv_profile: "nature_32_64_128",
    features_dim: "auto",
    state_net_arch: [64],
    fusion_features_dim: 768,
    layer_norm: true,
    activation: "relu",
    recurrent_enabled: true,
    recurrent_hidden_size: 256,
    recurrent_n_lstm_layers: 1,
    recurrent_shared_lstm: false,
    recurrent_enable_critic_lstm: true,
    pi_net_arch: [256, 128],
    vf_net_arch: [256, 128],
    gas_on_logit: 0.5,
  },
  reward: {
    time_penalty_per_frame: -0.005,
    reverse_time_penalty_scale: 2,
    low_speed_time_penalty_scale: 2,
    slow_speed_time_penalty_scale: 3,
    slow_speed_time_penalty_start_kph: 760,
    slow_speed_time_penalty_power: 1,
    progress_bucket_distance: 1000,
    progress_bucket_reward: 1,
    progress_reward_interval_frames: 1,
    airborne_progress_bucket_distance: 100,
    outside_bounds_reentry_progress_distance_cap: 10_000,
    airborne_offtrack_penalty_scale: 0.05,
    airborne_offtrack_recovery_reward_scale: 0.05,
    airborne_offtrack_recovery_requires_descending: true,
    airborne_offtrack_recovery_descend_epsilon: 1,
    lap_completion_bonus: 5,
    lap_position_scale: 1,
    energy_loss_epsilon: 0.01,
    energy_refill_progress_multiplier: 1,
    dirt_progress_multiplier: 1,
    ice_progress_multiplier: 1,
    dirt_entry_penalty: 0,
    ice_entry_penalty: 0,
    energy_refill_collision_cooldown_frames: 0,
    energy_full_refill_lap_bonus: 0,
    energy_full_refill_min_gain_fraction: 0,
    gas_underuse_penalty: 0,
    gas_underuse_threshold: 0.5,
    steer_oscillation_penalty: 0,
    steer_oscillation_deadzone: 0,
    steer_oscillation_cap: 2,
    steer_oscillation_power: 2,
    manual_boost_reward: 0.01,
    boost_pad_reward: 10,
    boost_pad_reward_progress_window: 800,
    lean_request_penalty: -0.003,
    lean_low_speed_penalty: -0.005,
    lean_low_speed_penalty_max_speed_kph: 750,
    airborne_pitch_up_penalty: -0.2,
    damage_taken_frame_penalty: 0,
    damage_taken_streak_ramp_penalty: 0,
    damage_taken_streak_cap_frames: 0,
    airborne_landing_reward: 0,
    collision_recoil_penalty: -4,
    failure_penalty: -30,
    truncation_penalty: -30,
    step_reward_clip_min: -100,
    step_reward_clip_max: 100,
  },
};

export const configMetadataFixture: ConfigMetadata = {
  observation_presets: [
    { value: "crop_60x76", label: "60 x 76", height: 60, width: 76 },
    { value: "crop_84x84", label: "84 x 84", height: 84, width: 84 },
  ],
  stack_modes: [
    { value: "rgb", label: "rgb" },
    { value: "gray", label: "gray" },
    { value: "luma_chroma", label: "luma chroma" },
  ],
  resize_filters: [
    { value: "nearest", label: "nearest" },
    { value: "bilinear", label: "bilinear" },
  ],
  progress_sources: [
    { value: "lap_progress", label: "lap progress" },
    { value: "segment_progress", label: "segment progress" },
    { value: "none", label: "none" },
  ],
  component_modes: [
    { value: "include", label: "include" },
    { value: "zero", label: "zero" },
    { value: "exclude", label: "exclude" },
  ],
  action_history_controls: [
    { value: "steer", label: "steer" },
    { value: "thrust", label: "thrust" },
    { value: "air_brake", label: "air brake" },
    { value: "boost", label: "boost" },
    { value: "lean", label: "lean" },
    { value: "pitch", label: "pitch" },
  ],
  state_components: [
    {
      name: "vehicle_state",
      label: "vehicle state",
      default_mode: "include",
      features: [
        { name: "vehicle_state.speed", low: 0, high: 2000 },
        { name: "vehicle_state.airborne", low: 0, high: 1 },
      ],
    },
    {
      name: "machine_context",
      label: "machine context",
      default_mode: "include",
      features: [{ name: "machine_context.weight", low: 0, high: 1 }],
    },
    {
      name: "track_position",
      label: "track position",
      default_mode: "include",
      features: [
        { name: "track_position.lap_progress", low: 0, high: 1 },
        { name: "track_position.edge_ratio", low: 0, high: 3 },
        { name: "track_position.outside_track_bounds", low: 0, high: 1 },
      ],
    },
    {
      name: "surface_state",
      label: "surface state",
      default_mode: "include",
      features: [{ name: "surface_state.on_dirt_surface", low: 0, high: 1 }],
    },
    {
      name: "course_context",
      label: "course context",
      default_mode: "include",
      features: [
        { name: "course_context.a", low: 0, high: 1 },
        { name: "course_context.b", low: 0, high: 1 },
      ],
    },
    {
      name: "control_history",
      label: "control history",
      default_mode: "include",
      features: [{ name: "control_history.steer_t_minus_1", low: -1, high: 1 }],
    },
  ],
  conv_profiles: [
    { value: "auto", label: "auto" },
    { value: "nature_32_64_128", label: "nature 32 64 128" },
  ],
  activation_functions: [
    { value: "relu", label: "relu" },
    { value: "gelu", label: "gelu" },
    { value: "tanh", label: "tanh" },
  ],
  net_arch_presets: [
    { value: "256,128", label: "[256, 128]" },
    { value: "512,256", label: "[512, 256]" },
  ],
};

export const policyPreviewFixture: PolicyArchitecturePreview = {
  image_shape: { height: 60, width: 76, channels: 6 },
  state_dim: 8,
  state_features: [
    { component: "vehicle_state", name: "vehicle_state.speed", mode: "include" },
    { component: "track_position", name: "track_position.edge_ratio", mode: "zero" },
  ],
  conv_layers: [
    {
      name: "conv1",
      in_channels: 6,
      out_channels: 32,
      kernel_size: 8,
      stride: 4,
      output_height: 14,
      output_width: 18,
      params: 12_320,
    },
  ],
  flatten_dim: 8064,
  image_features_dim: 8064,
  state_features_dim: 64,
  fusion_input_dim: 8128,
  extractor_output_dim: 768,
  policy_input_dim: 256,
  parameter_groups: [
    { name: "CNN convolutions", params: 12_320 },
    { name: "Fusion", params: 6_242_304 },
  ],
  total_params: 6_254_624,
  architecture_lanes: [
    {
      id: "image_branch",
      label: "Image branch",
      nodes: [
        { id: "image", label: "Image", detail: "60 x 76 x 6", tone: "normal" },
        { id: "cnn", label: "CNN", detail: "nature_32_64_128 → 8064", tone: "normal" },
      ],
    },
    {
      id: "state_branch",
      label: "State branch",
      nodes: [
        { id: "state", label: "State vector", detail: "8 scalars", tone: "normal" },
        { id: "state_mlp", label: "State MLP", detail: "8 → [64]", tone: "normal" },
      ],
    },
    {
      id: "fusion_and_heads",
      label: "Fusion and heads",
      nodes: [
        { id: "concat", label: "Concat", detail: "8128", tone: "normal" },
        { id: "fusion", label: "Fusion MLP", detail: "8128 → 768", tone: "normal" },
        { id: "layer_norm", label: "LayerNorm", detail: "on", tone: "normal" },
        { id: "lstm", label: "LSTM", detail: "768 → 256, 1 layer, actor + critic", tone: "normal" },
        {
          id: "policy_head",
          label: "Policy head",
          detail: "256 → [256, 128], relu",
          tone: "normal",
        },
        {
          id: "action_net",
          label: "Action net",
          detail: "128 → 1 continuous + 14 logits",
          tone: "normal",
        },
        { id: "value_head", label: "Value head", detail: "256 → [256, 128], relu", tone: "normal" },
        { id: "value_net", label: "Value net", detail: "128 → 1 value", tone: "normal" },
      ],
    },
  ],
};

export function draftFixture(overrides: Partial<ManagedDraft> = {}): ManagedDraft {
  return {
    id: "draft-001",
    name: "ppo_allcups_recurrent",
    created_at: "2026-05-01T16:11:28+00:00",
    updated_at: "2026-05-01T16:11:28+00:00",
    config: managedRunConfigFixture,
    ...overrides,
  };
}
