# src/rl_fzerox/core/training/runs/baseline_materializer/materialization/apply.py
from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from rl_fzerox.core.runtime_spec.schema import (
    CurriculumConfig,
    CurriculumStageConfig,
    TrackConfig,
    TrackSamplingConfig,
    TrackSamplingEntryConfig,
    TrainAppConfig,
)
from rl_fzerox.core.training.runs.baseline_materializer.materialization.baselines import (
    materialize_baseline_impl,
)
from rl_fzerox.core.training.runs.baseline_materializer.models import (
    BaselineArtifact,
    BaselineMaterializerContext,
    BaselineRequest,
    GenericModeSeedMaterializer,
    RaceStartMaterializer,
    StateSavingEmulator,
)
from rl_fzerox.core.training.runs.baseline_materializer.requests import (
    can_generate_track_config,
    request_from_track_config,
    request_from_track_entry,
)
from rl_fzerox.core.training.runs.baseline_materializer.settings import (
    BASELINE_MATERIALIZER_SETTINGS,
)
from rl_fzerox.core.training.runs.paths import RunPaths
from rl_fzerox.core.training.runs.track_baselines import (
    single_active_track_entry,
    track_config_from_sampling_entry,
)


def materialize_run_baselines_impl(
    config: TrainAppConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path | None,
    startup_reporter: Callable[[str, str], None] | None,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrainAppConfig:
    resolved_cache_root = (
        (cache_root or BASELINE_MATERIALIZER_SETTINGS.cache_root).expanduser().resolve()
    )
    context = BaselineMaterializerContext(
        core_path=config.emulator.core_path,
        rom_path=config.emulator.rom_path,
        renderer=config.emulator.renderer,
        race_intro_target_timer=config.env.race_intro_target_timer,
    )
    track_config = config.track
    emulator_baseline_path = config.emulator.baseline_state_path
    emulator_baseline_artifact: BaselineArtifact | None = None
    if not config.env.track_sampling.enabled and can_generate_track_config(track_config):
        track_request = request_from_track_config(
            track_config,
            camera_setting=config.env.camera_setting,
            fallback_label="track",
        )
        _report_startup(
            startup_reporter,
            "startup_materialize",
            _track_baseline_message(track_config),
        )
        emulator_baseline_artifact = materialize_baseline_impl(
            track_request,
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
            emulator_type=emulator_type,
            generic_mode_seed_materializer=generic_mode_seed_materializer,
            menu_seed_race_start_materializer=menu_seed_race_start_materializer,
        )
        emulator_baseline_path = emulator_baseline_artifact.state_path
        track_config = track_config.model_copy(
            update=_materialized_request_update(
                request=track_request,
                artifact=emulator_baseline_artifact,
            )
        )
    elif track_config.baseline_state_path is not None:
        track_request = request_from_track_config(
            track_config,
            camera_setting=config.env.camera_setting,
            fallback_label="track",
        )
        _report_startup(
            startup_reporter,
            "startup_materialize",
            _track_baseline_message(track_config),
        )
        emulator_baseline_artifact = materialize_baseline_impl(
            track_request,
            run_paths=run_paths,
            cache_root=resolved_cache_root,
            context=context,
            emulator_type=emulator_type,
            generic_mode_seed_materializer=generic_mode_seed_materializer,
            menu_seed_race_start_materializer=menu_seed_race_start_materializer,
        )
        emulator_baseline_path = emulator_baseline_artifact.state_path
        track_config = track_config.model_copy(
            update=_materialized_request_update(
                request=track_request,
                artifact=emulator_baseline_artifact,
            )
        )
    if emulator_baseline_path is not None and emulator_baseline_artifact is None:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {emulator_baseline_path}"
        )

    track_sampling_config = _materialize_track_sampling(
        config.env.track_sampling,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        startup_reporter=startup_reporter,
        sampling_label="track sampling",
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    single_track_entry = single_active_track_entry(track_sampling_config)
    if single_track_entry is not None:
        track_config = track_config_from_sampling_entry(
            single_track_entry,
            fallback=track_config,
        )

    env_config = config.env.model_copy(update={"track_sampling": track_sampling_config})
    curriculum_config = _materialize_curriculum(
        config.curriculum,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        startup_reporter=startup_reporter,
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )

    _report_startup(
        startup_reporter,
        "startup_materialize",
        "Run-local baseline materialization complete",
    )

    return config.model_copy(
        update={
            "track": track_config,
            "emulator": config.emulator.model_copy(
                update={
                    "runtime_dir": run_paths.runtime_root,
                    "baseline_state_path": emulator_baseline_path,
                }
            ),
            "env": env_config,
            "curriculum": curriculum_config,
        }
    )


def _materialize_curriculum(
    config: CurriculumConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    startup_reporter: Callable[[str, str], None] | None,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> CurriculumConfig:
    stages: list[CurriculumStageConfig] = []
    changed = False
    for stage_index, stage in enumerate(config.stages, start=1):
        if stage.track_sampling is None:
            stages.append(stage)
            continue
        changed = True
        stages.append(
            stage.model_copy(
                update={
                    "track_sampling": _materialize_track_sampling(
                        stage.track_sampling,
                        run_paths=run_paths,
                        cache_root=cache_root,
                        camera_setting=camera_setting,
                        context=context,
                        startup_reporter=startup_reporter,
                        sampling_label=f"curriculum stage {stage_index}",
                        emulator_type=emulator_type,
                        generic_mode_seed_materializer=generic_mode_seed_materializer,
                        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
                    )
                }
            )
        )
    if not changed:
        return config
    return config.model_copy(update={"stages": tuple(stages)})


def _materialize_track_sampling(
    config: TrackSamplingConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    startup_reporter: Callable[[str, str], None] | None,
    sampling_label: str,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrackSamplingConfig:
    if not config.entries:
        return config
    total_entries = len(config.entries)
    _report_startup(
        startup_reporter,
        "startup_materialize",
        f"Materializing {sampling_label} baselines for {total_entries} entries",
    )
    entries: list[TrackSamplingEntryConfig] = []
    for entry_index, entry in enumerate(config.entries, start=1):
        _report_startup(
            startup_reporter,
            "startup_materialize",
            _track_sampling_progress_message(
                sampling_label=sampling_label,
                entry=entry,
                complete_count=entry_index - 1,
                total_entries=total_entries,
            ),
        )
        entries.append(
            _materialized_track_sampling_entry(
                entry,
                run_paths=run_paths,
                cache_root=cache_root,
                camera_setting=camera_setting,
                context=context,
                emulator_type=emulator_type,
                generic_mode_seed_materializer=generic_mode_seed_materializer,
                menu_seed_race_start_materializer=menu_seed_race_start_materializer,
            )
        )
    return config.model_copy(update={"entries": tuple(entries)})


def _materialized_track_sampling_entry(
    entry: TrackSamplingEntryConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrackSamplingEntryConfig:
    request = request_from_track_entry(entry, camera_setting=camera_setting)
    artifact = materialize_baseline_impl(
        request,
        run_paths=run_paths,
        cache_root=cache_root,
        context=context,
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    return entry.model_copy(
        update=_materialized_request_update(
            request=request,
            artifact=artifact,
        )
    )


def _materialized_request_update(
    *,
    request: BaselineRequest,
    artifact: BaselineArtifact,
) -> dict[str, object]:
    update: dict[str, object] = {"baseline_state_path": artifact.state_path}
    if artifact.source_course_index is not None:
        update["source_course_index"] = artifact.source_course_index
    elif request.course_index is not None:
        update["source_course_index"] = request.course_index
    if artifact.source_vehicle is not None:
        update["source_vehicle"] = artifact.source_vehicle
    elif request.vehicle is not None:
        update["source_vehicle"] = request.vehicle
    if artifact.source_gp_difficulty is not None:
        update["source_gp_difficulty"] = artifact.source_gp_difficulty
    elif request.gp_difficulty is not None:
        update["source_gp_difficulty"] = request.gp_difficulty
    if artifact.source_engine_setting is not None:
        update["source_engine_setting"] = artifact.source_engine_setting
    elif request.engine_setting is not None:
        update["source_engine_setting"] = request.engine_setting
    if artifact.source_engine_setting_raw_value is not None:
        update["source_engine_setting_raw_value"] = artifact.source_engine_setting_raw_value
    elif request.engine_setting_raw_value is not None:
        update["source_engine_setting_raw_value"] = request.engine_setting_raw_value
    return update


def _track_sampling_progress_message(
    *,
    sampling_label: str,
    entry: TrackSamplingEntryConfig,
    complete_count: int,
    total_entries: int,
) -> str:
    course_label = entry.course_name or entry.display_name or entry.course_id or entry.id
    return (
        f"Materializing {sampling_label} baselines: "
        f"{complete_count}/{total_entries} complete; next {course_label}"
    )


def _report_startup(
    startup_reporter: Callable[[str, str], None] | None,
    kind: str,
    message: str,
) -> None:
    if startup_reporter is not None:
        startup_reporter(kind, message)


def _track_baseline_message(config: TrackConfig) -> str:
    course_label = config.course_name or config.course_id or "configured course"
    race_mode = config.mode or "configured mode"
    return f"Materializing race-start baseline for {course_label} ({race_mode})"
