# src/rl_fzerox/core/training/runs/baseline_materializer/materialization/apply.py
from __future__ import annotations

import hashlib
from collections.abc import Callable
from pathlib import Path

from rl_fzerox.core.runtime_spec.schema import (
    TrackConfig,
    TrackSamplingConfig,
    TrackSamplingEntryConfig,
    TrainAppConfig,
)
from rl_fzerox.core.training.runs.baseline_materializer.cache import sha256_file
from rl_fzerox.core.training.runs.baseline_materializer.materialization.baselines import (
    materialize_baseline_impl,
)
from rl_fzerox.core.training.runs.baseline_materializer.models import (
    BaselineArtifact,
    BaselineMaterializerContext,
    GenericModeSeedMaterializer,
    RaceStartMaterializer,
    StateSavingEmulator,
)
from rl_fzerox.core.training.runs.baseline_materializer.projection import (
    baseline_artifact_entry_update,
)
from rl_fzerox.core.training.runs.baseline_materializer.requests import (
    can_generate_track_config,
    request_from_track_config,
    request_from_track_entry,
)
from rl_fzerox.core.training.runs.baseline_materializer.settings import (
    BASELINE_MATERIALIZER_SETTINGS,
)
from rl_fzerox.core.training.runs.paths import RunPaths
from rl_fzerox.core.training.runs.track_baselines import (
    single_active_track_entry,
    track_config_from_sampling_entry,
)


def materialize_run_baselines_impl(
    config: TrainAppConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path | None,
    startup_reporter: Callable[[str, str], None] | None,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrainAppConfig:
    """Resolve every configured reset baseline to run-local state files.

    Managed training treats the run config as the source of truth. This pass may
    reuse global cache states, but the returned config always points at files
    owned by the current run so later archive/export/delete operations do not
    depend on cache retention.
    """

    resolved_cache_root = (
        (cache_root or BASELINE_MATERIALIZER_SETTINGS.cache_root).expanduser().resolve()
    )
    context = BaselineMaterializerContext(
        core_path=config.emulator.core_path,
        rom_path=config.emulator.rom_path,
        renderer=config.emulator.renderer,
        race_intro_target_timer=config.env.race_intro_target_timer,
        core_sha256=sha256_file(config.emulator.core_path),
        rom_sha256=sha256_file(config.emulator.rom_path),
    )
    track_config = config.track
    emulator_baseline_path = config.emulator.baseline_state_path
    track_config, emulator_baseline_artifact = _materialize_primary_track_baseline(
        track_config,
        track_sampling_enabled=config.env.track_sampling.enabled,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        startup_reporter=startup_reporter,
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    if emulator_baseline_artifact is not None:
        emulator_baseline_path = emulator_baseline_artifact.state_path
    if emulator_baseline_path is not None and emulator_baseline_artifact is None:
        raise ValueError(
            "Fresh training baselines must be generated by the materializer, not copied "
            f"from existing state files: {emulator_baseline_path}"
        )

    track_sampling_config = _materialize_track_sampling(
        config.env.track_sampling,
        run_paths=run_paths,
        cache_root=resolved_cache_root,
        camera_setting=config.env.camera_setting,
        context=context,
        startup_reporter=startup_reporter,
        sampling_label="track sampling",
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    single_track_entry = single_active_track_entry(track_sampling_config)
    if single_track_entry is not None:
        track_config = track_config_from_sampling_entry(
            single_track_entry,
            fallback=track_config,
        )

    env_config = config.env.model_copy(update={"track_sampling": track_sampling_config})
    _report_startup(
        startup_reporter,
        "startup_materialize",
        "Run-local baseline materialization complete",
    )

    return config.model_copy(
        update={
            "track": track_config,
            "emulator": config.emulator.model_copy(
                update={
                    "runtime_dir": run_paths.runtime_root,
                    "baseline_state_path": emulator_baseline_path,
                }
            ),
            "env": env_config,
        }
    )


def _materialize_primary_track_baseline(
    track_config: TrackConfig,
    *,
    track_sampling_enabled: bool,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    startup_reporter: Callable[[str, str], None] | None,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> tuple[TrackConfig, BaselineArtifact | None]:
    if not _should_materialize_primary_track_baseline(
        track_config,
        track_sampling_enabled=track_sampling_enabled,
    ):
        return track_config, None
    track_request = request_from_track_config(
        track_config,
        camera_setting=camera_setting,
        fallback_label="track",
    )
    _report_startup(
        startup_reporter,
        "startup_materialize",
        _track_baseline_message(track_config),
    )
    artifact = materialize_baseline_impl(
        track_request,
        run_paths=run_paths,
        cache_root=cache_root,
        context=context,
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    return (
        track_config.model_copy(
            update=baseline_artifact_entry_update(artifact=artifact, request=track_request)
        ),
        artifact,
    )


def _should_materialize_primary_track_baseline(
    track_config: TrackConfig,
    *,
    track_sampling_enabled: bool,
) -> bool:
    if not track_sampling_enabled and can_generate_track_config(track_config):
        return True
    return track_config.baseline_state_path is not None


def _materialize_track_sampling(
    config: TrackSamplingConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    startup_reporter: Callable[[str, str], None] | None,
    sampling_label: str,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrackSamplingConfig:
    """Materialize track-sampling entries after expanding reset variants."""

    if not config.entries:
        return config
    entries_to_materialize = _expanded_baseline_variant_entries(
        config.entries,
        baseline_variant_count=config.baseline_variant_count,
    )
    total_entries = len(entries_to_materialize)
    _report_startup(
        startup_reporter,
        "startup_materialize",
        f"Materializing {sampling_label} baselines for {total_entries} entries",
    )
    entries: list[TrackSamplingEntryConfig] = []
    for entry_index, entry in enumerate(entries_to_materialize, start=1):
        _report_startup(
            startup_reporter,
            "startup_materialize",
            _track_sampling_progress_message(
                sampling_label=sampling_label,
                entry=entry,
                complete_count=entry_index - 1,
                total_entries=total_entries,
            ),
        )
        entries.append(
            _materialized_track_sampling_entry(
                entry,
                run_paths=run_paths,
                cache_root=cache_root,
                camera_setting=camera_setting,
                context=context,
                emulator_type=emulator_type,
                generic_mode_seed_materializer=generic_mode_seed_materializer,
                menu_seed_race_start_materializer=menu_seed_race_start_materializer,
            )
        )
    return config.model_copy(update={"entries": tuple(entries)})


def _expanded_baseline_variant_entries(
    entries: tuple[TrackSamplingEntryConfig, ...],
    *,
    baseline_variant_count: int,
) -> tuple[TrackSamplingEntryConfig, ...]:
    if baseline_variant_count <= 1:
        return entries
    expanded: list[TrackSamplingEntryConfig] = []
    for entry in entries:
        if not _entry_supports_baseline_variants(entry):
            expanded.append(entry)
            continue
        expanded.extend(
            _baseline_variant_entry(
                entry,
                baseline_variant_index=variant_index,
                baseline_variant_count=baseline_variant_count,
            )
            for variant_index in range(baseline_variant_count)
        )
    return tuple(expanded)


def _entry_supports_baseline_variants(entry: TrackSamplingEntryConfig) -> bool:
    # Only built-in GP race starts have shuffled opponent grids. Time Attack has
    # no opponents, X Cup already gets course-generation seeds, and alt
    # baselines should preserve the captured state exactly.
    return (
        entry.mode == "gp_race"
        and entry.alt_baseline_id is None
        and entry.generated_course_kind is None
        and entry.course_index is not None
        and entry.vehicle is not None
    )


def _baseline_variant_entry(
    entry: TrackSamplingEntryConfig,
    *,
    baseline_variant_index: int,
    baseline_variant_count: int,
) -> TrackSamplingEntryConfig:
    # Variant entries share a scheduler group, so course-level weight overrides
    # still target one course while resets fan out across its materialized grids.
    update: dict[str, object] = {
        "weight": float(entry.weight) / baseline_variant_count,
        "baseline_group_id": entry.baseline_group_id or entry.id,
        "baseline_group_weight": 1.0,
        "baseline_variant_index": baseline_variant_index,
        "baseline_variant_count": baseline_variant_count,
    }
    if baseline_variant_index > 0:
        update["id"] = f"{entry.id}__variant_{baseline_variant_index + 1}"
        update["baseline_variant_seed"] = _baseline_variant_seed(
            entry,
            baseline_variant_index=baseline_variant_index,
        )
    return entry.model_copy(update=update)


def _baseline_variant_seed(
    entry: TrackSamplingEntryConfig,
    *,
    baseline_variant_index: int,
) -> int:
    """Derive stable reusable opponent-grid seeds without sharing RNG state."""

    parts = (
        "baseline_variant",
        entry.id,
        str(entry.course_id or ""),
        str(entry.runtime_course_key or ""),
        str(entry.course_index if entry.course_index is not None else ""),
        str(entry.gp_difficulty or ""),
        str(entry.vehicle or ""),
        str(baseline_variant_index),
    )
    digest = hashlib.blake2s("|".join(parts).encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, byteorder="big", signed=False)


def _materialized_track_sampling_entry(
    entry: TrackSamplingEntryConfig,
    *,
    run_paths: RunPaths,
    cache_root: Path,
    camera_setting: str | None,
    context: BaselineMaterializerContext,
    emulator_type: Callable[..., StateSavingEmulator],
    generic_mode_seed_materializer: GenericModeSeedMaterializer,
    menu_seed_race_start_materializer: RaceStartMaterializer,
) -> TrackSamplingEntryConfig:
    request = request_from_track_entry(entry, camera_setting=camera_setting)
    artifact = materialize_baseline_impl(
        request,
        run_paths=run_paths,
        cache_root=cache_root,
        context=context,
        emulator_type=emulator_type,
        generic_mode_seed_materializer=generic_mode_seed_materializer,
        menu_seed_race_start_materializer=menu_seed_race_start_materializer,
    )
    return entry.model_copy(
        update=baseline_artifact_entry_update(artifact=artifact, request=request)
    )


def _track_sampling_progress_message(
    *,
    sampling_label: str,
    entry: TrackSamplingEntryConfig,
    complete_count: int,
    total_entries: int,
) -> str:
    course_label = entry.course_name or entry.display_name or entry.course_id or entry.id
    return (
        f"Materializing {sampling_label} baselines: "
        f"{complete_count}/{total_entries} complete; next {course_label}"
    )


def _report_startup(
    startup_reporter: Callable[[str, str], None] | None,
    kind: str,
    message: str,
) -> None:
    if startup_reporter is not None:
        startup_reporter(kind, message)


def _track_baseline_message(config: TrackConfig) -> str:
    course_label = config.course_name or config.course_id or "configured course"
    race_mode = config.mode or "configured mode"
    return f"Materializing race-start baseline for {course_label} ({race_mode})"
