# tests/ui/viewer_support.py
from fzerox_emulator import FZeroXTelemetry
from tests.support.native_objects import make_telemetry


def sample_telemetry(
    *,
    state_labels: tuple[str, ...] = ("active",),
    state_flags: int | None = None,
    reverse_timer: int = 0,
    boost_timer: int = 0,
    difficulty_raw: int = 0,
    difficulty_name: str = "novice",
    camera_setting_raw: int = 2,
    camera_setting_name: str = "regular",
    energy: float = 178.0,
    max_energy: float = 178.0,
    recoil_tilt_magnitude: float = 0.0,
    damage_rumble_counter: int = 0,
    race_time_ms: int = 116,
    position: int = 30,
    total_racers: int = 30,
    lap_distance: float = 75_987.2,
    course_length: float = 80_000.0,
    segment_index: int | None = None,
    segment_t: float = 0.0,
    segment_length_proportion: float = 0.0,
    local_lateral_velocity: float = 0.0,
    signed_lateral_offset: float = 0.0,
    lateral_distance: float = 0.0,
    lateral_displacement_magnitude: float = 0.0,
    current_radius_left: float = 0.0,
    current_radius_right: float = 0.0,
    height_above_ground: float = 0.0,
    velocity_magnitude: float = 0.0,
    acceleration_magnitude: float = 0.0,
    acceleration_force: float = 0.0,
    drift_attack_force: float = 0.0,
    collision_mass: float = 0.0,
) -> FZeroXTelemetry:
    return make_telemetry(
        state_labels=state_labels,
        state_flags=state_flags,
        speed_kph=0.0,
        reverse_timer=reverse_timer,
        boost_timer=boost_timer,
        difficulty_raw=difficulty_raw,
        difficulty_name=difficulty_name,
        camera_setting_raw=camera_setting_raw,
        camera_setting_name=camera_setting_name,
        energy=energy,
        max_energy=max_energy,
        recoil_tilt_magnitude=recoil_tilt_magnitude,
        damage_rumble_counter=damage_rumble_counter,
        race_distance=-3040.8,
        lap_distance=lap_distance,
        race_time_ms=race_time_ms,
        position=position,
        total_racers=total_racers,
        course_length=course_length,
        segment_index=segment_index,
        segment_t=segment_t,
        segment_length_proportion=segment_length_proportion,
        local_lateral_velocity=local_lateral_velocity,
        signed_lateral_offset=signed_lateral_offset,
        lateral_distance=lateral_distance,
        lateral_displacement_magnitude=lateral_displacement_magnitude,
        current_radius_left=current_radius_left,
        current_radius_right=current_radius_right,
        height_above_ground=height_above_ground,
        velocity_magnitude=velocity_magnitude,
        acceleration_magnitude=acceleration_magnitude,
        acceleration_force=acceleration_force,
        drift_attack_force=drift_attack_force,
        collision_mass=collision_mass,
    )
