# src/rl_fzerox/_native.pyi
class Emulator:
    def __init__(self, core_path: str, rom_path: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def native_fps(self) -> float: ...
    @property
    def display_aspect_ratio(self) -> float: ...
    @property
    def frame_shape(self) -> tuple[int, int, int]: ...
    @property
    def frame_index(self) -> int: ...
    def reset(self) -> None: ...
    def step_frames(self, count: int = 1) -> None: ...
    def frame_rgb(self) -> bytes: ...
    def close(self) -> None: ...

class CoreInfo:
    api_version: int
    library_name: str
    library_version: str
    valid_extensions: list[str]
    requires_full_path: bool
    blocks_extract: bool

def probe_core(core_path: str) -> CoreInfo: ...
