# src/rl_fzerox/core/manager/artifacts/tensorboard_views.py
"""Filesystem builder for generated TensorBoard lineage views."""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from rl_fzerox.core.manager.models import ManagedRun
from rl_fzerox.core.training.runs import RUN_LAYOUT

UNGROUPED_LINEAGE_GROUP = "Ungrouped"
_VIEW_ROOT_MARKER = ".rl_fzerox_tensorboard_views"


@dataclass(frozen=True, slots=True)
class TensorboardViewGroup:
    name: str
    slug: str
    path: Path
    lineage_count: int
    run_count: int


def rebuild_tensorboard_views(
    runs: tuple[ManagedRun, ...],
    *,
    view_root: Path,
) -> tuple[TensorboardViewGroup, ...]:
    """Rebuild symlink-only TensorBoard logdir views grouped by lineage metadata."""

    resolved_view_root = view_root.expanduser().resolve()
    _clear_view_root(resolved_view_root)
    resolved_view_root.mkdir(parents=True, exist_ok=True)
    (resolved_view_root / _VIEW_ROOT_MARKER).write_text(
        "Generated by rl-fzerox. Safe to delete.\n",
        encoding="utf-8",
    )

    groups: dict[str, list[tuple[ManagedRun, str]]] = {}
    for lineage_id, lineage_runs in _runs_by_lineage(runs).items():
        for group_name in _lineage_group_names(lineage_runs):
            groups.setdefault(group_name, []).extend((run, lineage_id) for run in lineage_runs)

    view_groups: list[TensorboardViewGroup] = []
    for group_name, group_runs in sorted(groups.items(), key=lambda item: _group_sort_key(item[0])):
        group_slug = slugify_path_segment(group_name)
        group_path = resolved_view_root / group_slug
        lineage_ids = {lineage_id for _, lineage_id in group_runs}
        for lineage_id in sorted(lineage_ids):
            lineage_runs = tuple(run for run, current_id in group_runs if current_id == lineage_id)
            lineage_path = group_path / _lineage_path_segment(lineage_id, lineage_runs)
            lineage_path.mkdir(parents=True, exist_ok=True)
            for run in sorted(lineage_runs, key=lambda item: (item.created_at, item.id)):
                link_path = lineage_path / _run_path_segment(run)
                target_path = (run.run_dir / RUN_LAYOUT.tensorboard_dirname).expanduser().resolve()
                _replace_symlink(link_path=link_path, target_path=target_path)
        view_groups.append(
            TensorboardViewGroup(
                name=group_name,
                slug=group_slug,
                path=group_path,
                lineage_count=len(lineage_ids),
                run_count=len(group_runs),
            )
        )
    return tuple(view_groups)


def slugify_path_segment(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "unnamed"


def _clear_view_root(view_root: Path) -> None:
    if not view_root.exists() and not view_root.is_symlink():
        return
    if view_root.is_symlink() or view_root.is_file():
        raise RuntimeError(f"refusing to replace non-directory TensorBoard view root: {view_root}")
    if not _is_generated_view_tree(view_root):
        raise RuntimeError(f"refusing to clear unowned TensorBoard view root: {view_root}")
    shutil.rmtree(view_root)


def _is_generated_view_tree(view_root: Path) -> bool:
    marker = view_root / _VIEW_ROOT_MARKER
    if marker.is_file():
        return True
    for path in view_root.rglob("*"):
        if path.is_symlink() or path.is_dir():
            continue
        if path.name == _VIEW_ROOT_MARKER:
            continue
        return False
    return True


def _runs_by_lineage(runs: tuple[ManagedRun, ...]) -> dict[str, tuple[ManagedRun, ...]]:
    buckets: dict[str, list[ManagedRun]] = {}
    for run in runs:
        buckets.setdefault(run.lineage_id, []).append(run)
    return {lineage_id: tuple(lineage_runs) for lineage_id, lineage_runs in buckets.items()}


def _lineage_group_names(lineage_runs: tuple[ManagedRun, ...]) -> tuple[str, ...]:
    for run in lineage_runs:
        if run.lineage_groups:
            return run.lineage_groups
    return (UNGROUPED_LINEAGE_GROUP,)


def _lineage_path_segment(lineage_id: str, lineage_runs: tuple[ManagedRun, ...]) -> str:
    root_run = min(lineage_runs, key=lambda run: (run.created_at, run.id))
    return f"{slugify_path_segment(root_run.name)}__{lineage_id}"


def _run_path_segment(run: ManagedRun) -> str:
    return f"{slugify_path_segment(run.name)}__{run.id}"


def _replace_symlink(*, link_path: Path, target_path: Path) -> None:
    if link_path.exists() or link_path.is_symlink():
        if link_path.is_dir() and not link_path.is_symlink():
            shutil.rmtree(link_path)
        else:
            link_path.unlink()
    link_path.symlink_to(target_path, target_is_directory=True)


def _group_sort_key(group_name: str) -> tuple[int, str]:
    return (1 if group_name == UNGROUPED_LINEAGE_GROUP else 0, group_name.lower())
