defaults:
  - /train_ppo_base
  - /local/train.local.base@_global_
  - _self_

env:
  action:
    name: steer_drive_boost_shoulder

train:
  init_run_dir: local/runs/ppo_cnn_0043
  init_artifact: latest
