defaults:
  - /train_ppo_base
  - _self_

emulator:
  baseline_state_path: local/states/first-race.state
  renderer: angrylion

env:
  action:
    name: steer_drive_boost_shoulder

policy:
  activation: tanh

train:
  vec_env: dummy
  num_envs: 1
  output_root: local/runs
