defaults:
  - /train
  - _self_

seed: 123

emulator:
  baseline_state_path: local/states/first-race.state
  renderer: angrylion

env:
  action:
    name: steer_drive_boost_drift

policy:
  activation: tanh

train:
  vec_env: dummy
  num_envs: 1
  output_root: local/runs
  run_name: ppo_cnn
