defaults:
  - /train_ppo_base
  - /local/train.local.base@_global_
  - _self_

train:
  algorithm: maskable_recurrent_ppo
  init_run_dir: local/runs/ppo_cnn_0054
  init_artifact: latest
  ent_coef: 0.0

env:
  action:
    name: steer_drive_boost_drift
  boost_min_energy_fraction: 0.30

policy:
  recurrent:
    enabled: true
    hidden_size: 512
    n_lstm_layers: 1
    shared_lstm: false
    enable_critic_lstm: true
